language: java
jdk:
- openjdk8
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy >/dev/null
    2>&1
  skip_cleanup: true
  on:
    repo: AuScope/portal-core
    branch: master
